### PR TITLE
Update to Spine v1.8 and address security vulnarabilities

### PR DESCRIPTION
**Pull request by dmdashenkov**
We update Java and JS dependencies to address piled up security warnings.

The version of Spine is updated to 1.8.0.

### CODE REVIEW

**Comment by dmdashenkov** [comment]
@armiol, PTAL.

**Review by armiol — APPROVED** [review]
@dmdashenkov LGTM. Let's continue with the rest of examples, please.

**Comment by armiol** [comment]
@dmdashenkov I also think we should migrate the examples to GitHub Actions. Travis does not seem to be relevant for Spine-related projects anymore.

**Comment by dmdashenkov** [comment]
@armiol, will migrate to GitHub Actions in a separate PR just for clarity's sake.

**Pull request merged**
